name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # รันทุกวัน เที่ยงคืน UTC
  workflow_dispatch:        # กด Run manually ได้

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: RewSuphakit
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
